version: "3"

services:
  java-app:
    image: hazelcast-test:latest
    ports:
      - 8080:8080
    environment:
      - HAZELCAST_ENDPOINTS=hazelcast
      - POSTGRES_DATABASE_HOST=postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/
  hazelcast:
    image: hazelcast/hazelcast
    ports:
      - 5701:5701
  hazelcast-management-center:
    image: hazelcast/management-center
    ports:
      - 8081:8080

volumes:
  postgres-db-data:
