version: "3"

services:
  java-app:
    image: hazelcast-test:latest
    ports:
      - 8080:8080
    environment:
      - HAZELCAST_ENDPOINTS=hazelcast
  hazelcast:
    image: hazelcast/hazelcast
    ports:
      - 5701:5701
  hazelcast-management-center:
    image: hazelcast/management-center
    ports:
      - 8081:8080
